version: '2'

services:
  config-server:
    image: jamessu712/cloud-config-server
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: jamessu712/cloud-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8761:8761

  biz-service:
    image: jamessu712/mall-biz-service
    container_name: biz-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
    - 8081:8081

#  web-service:
#    image: jamessu712/mall-web-service
#    container_name: web-service
#    mem_limit: 512M
#    depends_on:
#     - config-server
#     - discovery-server
#    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
#    ports:
#     - 8082:8082

#  api-gateway:
#    image: jamessu712/cloud-gateway-server
#    container_name: api-gateway
#    mem_limit: 512M
#    depends_on:
#     - config-server
#     - discovery-server
#    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
#    ports:
#     - 8080:8080

#  tracing-server:
#    image: openzipkin/zipkin
#    container_name: tracing-server
#    mem_limit: 512M
#    environment:
#    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
#    ports:
#     - 9411:9411

#  admin-server:
#    image: jamessu712/cloud-admin-server
#    container_name: admin-server
#    mem_limit: 512M
#    depends_on:
#     - config-server
#     - discovery-server
#    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
#    ports:
#     - 9090:9090
#
#  ## Grafana / Prometheus
#
#  grafana-server:
#    image: jamessu712/grafana-server
#    build: ./docker/grafana
#    container_name: grafana-server
#    mem_limit: 256M
#    ports:
#    - 3000:3000
#
#  prometheus-server:
#    image: jamessu712/prometheus-server
#    build: ./docker/prometheus
#    container_name: prometheus-server
#    mem_limit: 256M
#    ports:
#    - 9091:9090
