spring:
  profiles: default
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
#  sleuth:
#    sampler:
#      percentage: 1.0
#  cloud:
#    config:
#      # Allow the microservices to override the remote properties with their own System properties or config file
#      allow-override: true
#      # Override configuration with any local property source
#      override-none: true

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    com.jamessu712: debug

---
#spring:
#  profiles: docker
#  zipkin:
#    baseUrl: http://tracing-server:9411
#server:
#  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server:8761/eureka/

